### ISSUE TITLE
How did you obtain the orientation of the agent?

### ISSUE THREAD

**Issue by zxyhhhappy** [QingrongH/LLM-TPC#2]
![image](https://github.com/QingrongH/LLM-TPC/assets/73413711/27f65171-302c-475a-98d6-df27401babed)

Thank you for your work. I would like to know if the angle here remains the default value in each situation when forming the sections? Does this angle represent the orientation of the agent? How did you obtain the orientation of the agent?

**Comment by QingrongH** [comment]
1. The angle here is the hyper-parameter used to define a polygon that represents the region for the allocentric relations (e.g. left) of the anchor object / agent. It does not represent the orientation of the agent.
![github](https://github.com/QingrongH/LLM-TPC/assets/98394854/10366426-d328-4f6c-a1dd-5a63500f111a)
2. The orientation of the agent is provided in the SQA3D dataset. Before entering the TPC loop, we transform the whole scene to the first person's perspective according to the position and orientation of the agent. After applying the transformation, the agent is located at the origin of the coordinates, with its line of sight parallel to the XY plane and pointing towards the positive y-axis.
![image](https://github.com/QingrongH/LLM-TPC/assets/98394854/891cfbc7-75cf-4cc7-a1b3-02d38597e432)

**Comment by zxyhhhappy** [comment]
get it! Thank you again for your excellent work.
